"""added on_shelf

Revision ID: b7d4aeca559d
Revises: db0ca72e8f69
Create Date: 2018-05-29 16:31:55.338848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d4aeca559d'
down_revision = 'db0ca72e8f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('on_shelf', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_book_on_shelf'), 'book', ['on_shelf'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_on_shelf'), table_name='book')
    op.drop_column('book', 'on_shelf')
    # ### end Alembic commands ###
